# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/cmake/bin/cmake

# The command to remove a file.
RM = /usr/local/cmake/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/yyt/mycode/Reactor

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/yyt/mycode/Reactor

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/cmake/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/cmake/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/yyt/mycode/Reactor/CMakeFiles /home/yyt/mycode/Reactor/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/yyt/mycode/Reactor/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ReactorServer

# Build rule for target.
ReactorServer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ReactorServer
.PHONY : ReactorServer

# fast build rule for target.
ReactorServer/fast:
	$(MAKE) -f CMakeFiles/ReactorServer.dir/build.make CMakeFiles/ReactorServer.dir/build
.PHONY : ReactorServer/fast

Channel.o: Channel.cpp.o

.PHONY : Channel.o

# target to build an object file
Channel.cpp.o:
	$(MAKE) -f CMakeFiles/ReactorServer.dir/build.make CMakeFiles/ReactorServer.dir/Channel.cpp.o
.PHONY : Channel.cpp.o

Channel.i: Channel.cpp.i

.PHONY : Channel.i

# target to preprocess a source file
Channel.cpp.i:
	$(MAKE) -f CMakeFiles/ReactorServer.dir/build.make CMakeFiles/ReactorServer.dir/Channel.cpp.i
.PHONY : Channel.cpp.i

Channel.s: Channel.cpp.s

.PHONY : Channel.s

# target to generate assembly for a file
Channel.cpp.s:
	$(MAKE) -f CMakeFiles/ReactorServer.dir/build.make CMakeFiles/ReactorServer.dir/Channel.cpp.s
.PHONY : Channel.cpp.s

Epoll.o: Epoll.cpp.o

.PHONY : Epoll.o

# target to build an object file
Epoll.cpp.o:
	$(MAKE) -f CMakeFiles/ReactorServer.dir/build.make CMakeFiles/ReactorServer.dir/Epoll.cpp.o
.PHONY : Epoll.cpp.o

Epoll.i: Epoll.cpp.i

.PHONY : Epoll.i

# target to preprocess a source file
Epoll.cpp.i:
	$(MAKE) -f CMakeFiles/ReactorServer.dir/build.make CMakeFiles/ReactorServer.dir/Epoll.cpp.i
.PHONY : Epoll.cpp.i

Epoll.s: Epoll.cpp.s

.PHONY : Epoll.s

# target to generate assembly for a file
Epoll.cpp.s:
	$(MAKE) -f CMakeFiles/ReactorServer.dir/build.make CMakeFiles/ReactorServer.dir/Epoll.cpp.s
.PHONY : Epoll.cpp.s

EventLoop.o: EventLoop.cpp.o

.PHONY : EventLoop.o

# target to build an object file
EventLoop.cpp.o:
	$(MAKE) -f CMakeFiles/ReactorServer.dir/build.make CMakeFiles/ReactorServer.dir/EventLoop.cpp.o
.PHONY : EventLoop.cpp.o

EventLoop.i: EventLoop.cpp.i

.PHONY : EventLoop.i

# target to preprocess a source file
EventLoop.cpp.i:
	$(MAKE) -f CMakeFiles/ReactorServer.dir/build.make CMakeFiles/ReactorServer.dir/EventLoop.cpp.i
.PHONY : EventLoop.cpp.i

EventLoop.s: EventLoop.cpp.s

.PHONY : EventLoop.s

# target to generate assembly for a file
EventLoop.cpp.s:
	$(MAKE) -f CMakeFiles/ReactorServer.dir/build.make CMakeFiles/ReactorServer.dir/EventLoop.cpp.s
.PHONY : EventLoop.cpp.s

InetAddress.o: InetAddress.cpp.o

.PHONY : InetAddress.o

# target to build an object file
InetAddress.cpp.o:
	$(MAKE) -f CMakeFiles/ReactorServer.dir/build.make CMakeFiles/ReactorServer.dir/InetAddress.cpp.o
.PHONY : InetAddress.cpp.o

InetAddress.i: InetAddress.cpp.i

.PHONY : InetAddress.i

# target to preprocess a source file
InetAddress.cpp.i:
	$(MAKE) -f CMakeFiles/ReactorServer.dir/build.make CMakeFiles/ReactorServer.dir/InetAddress.cpp.i
.PHONY : InetAddress.cpp.i

InetAddress.s: InetAddress.cpp.s

.PHONY : InetAddress.s

# target to generate assembly for a file
InetAddress.cpp.s:
	$(MAKE) -f CMakeFiles/ReactorServer.dir/build.make CMakeFiles/ReactorServer.dir/InetAddress.cpp.s
.PHONY : InetAddress.cpp.s

Socket.o: Socket.cpp.o

.PHONY : Socket.o

# target to build an object file
Socket.cpp.o:
	$(MAKE) -f CMakeFiles/ReactorServer.dir/build.make CMakeFiles/ReactorServer.dir/Socket.cpp.o
.PHONY : Socket.cpp.o

Socket.i: Socket.cpp.i

.PHONY : Socket.i

# target to preprocess a source file
Socket.cpp.i:
	$(MAKE) -f CMakeFiles/ReactorServer.dir/build.make CMakeFiles/ReactorServer.dir/Socket.cpp.i
.PHONY : Socket.cpp.i

Socket.s: Socket.cpp.s

.PHONY : Socket.s

# target to generate assembly for a file
Socket.cpp.s:
	$(MAKE) -f CMakeFiles/ReactorServer.dir/build.make CMakeFiles/ReactorServer.dir/Socket.cpp.s
.PHONY : Socket.cpp.s

TcpServer.o: TcpServer.cpp.o

.PHONY : TcpServer.o

# target to build an object file
TcpServer.cpp.o:
	$(MAKE) -f CMakeFiles/ReactorServer.dir/build.make CMakeFiles/ReactorServer.dir/TcpServer.cpp.o
.PHONY : TcpServer.cpp.o

TcpServer.i: TcpServer.cpp.i

.PHONY : TcpServer.i

# target to preprocess a source file
TcpServer.cpp.i:
	$(MAKE) -f CMakeFiles/ReactorServer.dir/build.make CMakeFiles/ReactorServer.dir/TcpServer.cpp.i
.PHONY : TcpServer.cpp.i

TcpServer.s: TcpServer.cpp.s

.PHONY : TcpServer.s

# target to generate assembly for a file
TcpServer.cpp.s:
	$(MAKE) -f CMakeFiles/ReactorServer.dir/build.make CMakeFiles/ReactorServer.dir/TcpServer.cpp.s
.PHONY : TcpServer.cpp.s

test.o: test.cpp.o

.PHONY : test.o

# target to build an object file
test.cpp.o:
	$(MAKE) -f CMakeFiles/ReactorServer.dir/build.make CMakeFiles/ReactorServer.dir/test.cpp.o
.PHONY : test.cpp.o

test.i: test.cpp.i

.PHONY : test.i

# target to preprocess a source file
test.cpp.i:
	$(MAKE) -f CMakeFiles/ReactorServer.dir/build.make CMakeFiles/ReactorServer.dir/test.cpp.i
.PHONY : test.cpp.i

test.s: test.cpp.s

.PHONY : test.s

# target to generate assembly for a file
test.cpp.s:
	$(MAKE) -f CMakeFiles/ReactorServer.dir/build.make CMakeFiles/ReactorServer.dir/test.cpp.s
.PHONY : test.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... ReactorServer"
	@echo "... Channel.o"
	@echo "... Channel.i"
	@echo "... Channel.s"
	@echo "... Epoll.o"
	@echo "... Epoll.i"
	@echo "... Epoll.s"
	@echo "... EventLoop.o"
	@echo "... EventLoop.i"
	@echo "... EventLoop.s"
	@echo "... InetAddress.o"
	@echo "... InetAddress.i"
	@echo "... InetAddress.s"
	@echo "... Socket.o"
	@echo "... Socket.i"
	@echo "... Socket.s"
	@echo "... TcpServer.o"
	@echo "... TcpServer.i"
	@echo "... TcpServer.s"
	@echo "... test.o"
	@echo "... test.i"
	@echo "... test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

